### ISSUE TITLE
Add support for Kubernetes annotations

### ISSUE THREAD

**Issue by zanetworker** [zanetworker/dockument#4]
Currently Dockument supports annotations for Dockerfiles, however, the scope of Dockument entails Kubernetes and Docker, therefore, it should be able to support YAML annotations for Kubernetes Objects. 

Example of a Dockument annotated Object YAML: 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-apparmor
  labels:
    app: nginx
  annotations:
    # Note that this is ignored if the Kubernetes node is not running version 1.4 or greater.
     container.apparmor.security.beta.kubernetes.io/nginx: localhost/k8s-nginx
     api.CONTAINERS.nginx: ""
     api.CONTAINERS.nginx.port: "80"
     api.CONTAINERS.nginx.image: "nginx"

     api.CONTAINERS.nginx-helper: ""
     api.CONTAINERS.nginx-helper.port: "1234"
     api.CONTAINERS.nginx-helper.image: "nginx"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
 - name: nginx-helper
    image: nginx
    ports: 
    - containerPort: 1234
```
